from typing import List, Dict, Any, Optional
from uuid import UUID
from datetime import datetime, timedelta, timezone
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select
from sqlalchemy import func, case, text, desc
from decimal import Decimal

from modules.intelligence.models import InventoryPolicy, PurchaseSuggestion, OperationalAlert
from modules.inventory.models import StockBalanceProjection, StockLedgerEntry, StockMovement
from modules.catalog.models import SKU
from modules.purchasing.models import PurchaseOrderLine, PurchaseOrder, SupplierInvoiceLine, GoodsReceiptLine, GoodsReceipt

class IntelligenceService:
    def __init__(self, session: AsyncSession):
        self.session = session

    async def calculate_abc_classification(self, tenant_id: UUID, location_id: UUID, days_history: int = 30) -> None:
        """
        Calculates ABC classification based on total consumption value over the last N days.
        Top 80% = A, Next 15% = B, Bottom 5% = C.
        Combines:
        1. Negative quantity in stock ledger for physical outflows (LOSS, PRODUCTION_CONSUMPTION).
        2. Theoretical consumption generated by POS recipe sales.
        Uses StockMovement and TheoreticalConsumption to accurately scope by transaction location.
        """
        cutoff_date = datetime.now(timezone.utc) - timedelta(days=days_history)
        
        # 1. Aggregate physical consumption value per SKU linked via StockMovement location
        stmt_physical = select(
            StockLedgerEntry.sku_id,
            func.sum(func.abs(StockLedgerEntry.quantity) * func.coalesce(StockLedgerEntry.unit_cost, Decimal(0))).label('physical_value')
        ).join(
            StockMovement, 
            StockLedgerEntry.movement_id == StockMovement.id
        ).where(
            StockLedgerEntry.tenant_id == tenant_id,
            StockMovement.location_id == location_id,
            StockLedgerEntry.quantity < 0,
            StockLedgerEntry.created_at >= cutoff_date
        ).group_by(StockLedgerEntry.sku_id)
        
        physical_results = (await self.session.execute(stmt_physical)).all()
        consumption_map: Dict[UUID, Decimal] = {r.sku_id: Decimal(str(r.physical_value or 0)) for r in physical_results}

        # 2. Aggregate theoretical sales consumption value per SKU
        from modules.inventory.models import TheoreticalConsumption
        stmt_theo = select(
            TheoreticalConsumption.sku_id,
            func.sum(TheoreticalConsumption.quantity * func.coalesce(TheoreticalConsumption.unit_cost_at_time, Decimal(0))).label('theo_value')
        ).where(
            TheoreticalConsumption.tenant_id == tenant_id,
            TheoreticalConsumption.created_at >= cutoff_date
        ).group_by(TheoreticalConsumption.sku_id)
        
        theo_results = (await self.session.execute(stmt_theo)).all()
        for r in theo_results:
            consumption_map[r.sku_id] = consumption_map.get(r.sku_id, Decimal(0)) + Decimal(str(r.theo_value or 0))
        
        if not consumption_map:
            return
            
        # 3. Sort and calculate cumulative percentages
        sku_values = [{'sku_id': k, 'value': v} for k, v in consumption_map.items()]
        sku_values.sort(key=lambda x: x['value'], reverse=True)
        
        total_consumption = sum(x['value'] for x in sku_values)
        if total_consumption == 0:
            return
            
        cumulative_value = Decimal(0)
        
        for item in sku_values:
            percentage_before = cumulative_value / total_consumption
            
            if percentage_before < Decimal('0.80'):
                abc = 'A'
            elif percentage_before < Decimal('0.95'):
                abc = 'B'
            else:
                abc = 'C'
                
            cumulative_value += item['value']
                
            # 4. Upsert InventoryPolicy
            stmt_policy = select(InventoryPolicy).where(
                InventoryPolicy.tenant_id == tenant_id,
                InventoryPolicy.location_id == location_id,
                InventoryPolicy.sku_id == item['sku_id']
            )
            policy = (await self.session.execute(stmt_policy)).scalar_one_or_none()
            
            if policy:
                policy.abc_class = abc
            else:
                policy = InventoryPolicy(
                    tenant_id=tenant_id,
                    location_id=location_id,
                    sku_id=item['sku_id'],
                    abc_class=abc
                )
                self.session.add(policy)
                
        await self.session.flush()

    async def generate_purchase_suggestions(self, tenant_id: UUID, location_id: UUID) -> List[PurchaseSuggestion]:
        """
        Generates deterministic purchase suggestions based on:
        Suggested Qty = Target Stock - On Hand - Expected Inbound (Approved PO lines not yet received)
        """
        # Get policies with targets > 0
        stmt = select(InventoryPolicy).where(
            InventoryPolicy.tenant_id == tenant_id,
            InventoryPolicy.location_id == location_id,
            InventoryPolicy.target_stock > 0
        )
        policies = (await self.session.execute(stmt)).scalars().all()
        
        generated = []
        for policy in policies:
            # 1. On Hand
            stmt_stock = select(StockBalanceProjection.quantity).where(
                StockBalanceProjection.tenant_id == tenant_id,
                StockBalanceProjection.location_id == location_id,
                StockBalanceProjection.sku_id == policy.sku_id
            )
            on_hand = (await self.session.execute(stmt_stock)).scalar_one_or_none() or Decimal(0)
            
            # 2. Expected Inbound (from Purchase Orders - case-insensitive check)
            stmt_po_lines = select(PurchaseOrderLine.id, PurchaseOrderLine.ordered_quantity).join(
                PurchaseOrder, PurchaseOrder.id == PurchaseOrderLine.purchase_order_id
            ).where(
                PurchaseOrderLine.tenant_id == tenant_id,
                PurchaseOrderLine.sku_id == policy.sku_id,
                PurchaseOrder.status.in_(['APPROVED', 'SENT', 'PARTIAL_RECEIPT', 'approved', 'sent', 'partial_receipt'])
            )
            po_lines_result = (await self.session.execute(stmt_po_lines)).all()
            
            inbound = Decimal(0)
            if po_lines_result:
                for row in po_lines_result:
                    stmt_rec = select(func.sum(GoodsReceiptLine.quantity)).where(
                        GoodsReceiptLine.tenant_id == tenant_id,
                        GoodsReceiptLine.purchase_order_line_id == row.id
                    )
                    received_qty = (await self.session.execute(stmt_rec)).scalar_one_or_none() or Decimal(0)
                    if row.ordered_quantity > received_qty:
                        inbound += (row.ordered_quantity - received_qty)
                        
            suggested = policy.target_stock - on_hand - inbound
            
            if suggested > 0:
                # Upsert suggestion
                stmt_sugg = select(PurchaseSuggestion).where(
                    PurchaseSuggestion.tenant_id == tenant_id,
                    PurchaseSuggestion.location_id == location_id,
                    PurchaseSuggestion.sku_id == policy.sku_id,
                    PurchaseSuggestion.status == 'PENDING'
                )
                existing = (await self.session.execute(stmt_sugg)).scalar_one_or_none()
                
                reason = f"Target({policy.target_stock}) - OnHand({on_hand}) - Inbound({inbound}) = {suggested}"
                if existing:
                    existing.suggested_quantity = suggested
                    existing.reason = reason
                    generated.append(existing)
                else:
                    new_sugg = PurchaseSuggestion(
                        tenant_id=tenant_id,
                        location_id=location_id,
                        sku_id=policy.sku_id,
                        suggested_quantity=suggested,
                        reason=reason
                    )
                    self.session.add(new_sugg)
                    generated.append(new_sugg)
                    
        await self.session.flush()
        return generated

    async def generate_operational_alerts(self, tenant_id: UUID, location_id: UUID) -> List[OperationalAlert]:
        """
        Generates alerts for stockouts (On Hand < Reorder Point).
        ROP = (Daily Baseline * Lead Time) + Min Stock.
        Approximates Daily Baseline by dividing the last 30 days consumption by 30 scoped via StockMovement.
        """
        cutoff_date = datetime.now(timezone.utc) - timedelta(days=30)
        
        stmt = select(InventoryPolicy).where(
            InventoryPolicy.tenant_id == tenant_id,
            InventoryPolicy.location_id == location_id
        )
        policies = (await self.session.execute(stmt)).scalars().all()
        
        alerts = []
        for policy in policies:
            # On Hand
            stmt_stock = select(StockBalanceProjection.quantity).where(
                StockBalanceProjection.tenant_id == tenant_id,
                StockBalanceProjection.location_id == location_id,
                StockBalanceProjection.sku_id == policy.sku_id
            )
            on_hand = (await self.session.execute(stmt_stock)).scalar_one_or_none() or Decimal(0)
            
            # Daily Baseline (Average over 30 days scoped to location by StockMovement)
            stmt_cons = select(func.sum(func.abs(StockLedgerEntry.quantity))).join(
                StockMovement, 
                StockLedgerEntry.movement_id == StockMovement.id
            ).where(
                StockLedgerEntry.tenant_id == tenant_id,
                StockMovement.location_id == location_id,
                StockLedgerEntry.quantity < 0,
                StockLedgerEntry.created_at >= cutoff_date,
                StockLedgerEntry.sku_id == policy.sku_id
            )
            monthly_consumption = (await self.session.execute(stmt_cons)).scalar_one_or_none() or Decimal(0)
            daily_baseline = monthly_consumption / Decimal(30)
            
            # Reorder Point
            rop = (daily_baseline * Decimal(policy.lead_time_days)) + policy.min_stock
            
            if on_hand < rop:
                # Avoid duplicates
                stmt_alert = select(OperationalAlert).where(
                    OperationalAlert.tenant_id == tenant_id,
                    OperationalAlert.location_id == location_id,
                    OperationalAlert.sku_id == policy.sku_id,
                    OperationalAlert.metric == 'STOCKOUT_RISK',
                    OperationalAlert.is_resolved == False
                )
                existing = (await self.session.execute(stmt_alert)).scalar_one_or_none()
                if not existing:
                    alert = OperationalAlert(
                        tenant_id=tenant_id,
                        location_id=location_id,
                        sku_id=policy.sku_id,
                        metric='STOCKOUT_RISK',
                        observed_value=on_hand,
                        reference_value=rop,
                        threshold=rop,
                        reason=f"On Hand ({on_hand}) is below ROP ({rop})"
                    )
                    self.session.add(alert)
                    alerts.append(alert)
                    
        await self.session.flush()
        return alerts

    async def check_purchase_price_variation(self, tenant_id: UUID, invoice_id: UUID) -> List[OperationalAlert]:
        """
        Check if the unit price on a SupplierInvoiceLine exceeds the historical average cost 
        (e.g., from StockLedgerEntry) by more than 10%.
        """
        stmt = select(SupplierInvoiceLine).where(
            SupplierInvoiceLine.tenant_id == tenant_id,
            SupplierInvoiceLine.invoice_id == invoice_id
        )
        lines = (await self.session.execute(stmt)).scalars().all()
        
        alerts = []
        for line in lines:
            if not line.sku_id:
                continue
                
            # Get latest moving average cost from stock ledger before this invoice (simplification: just get the latest unit_cost)
            # A true MA cost would look at balance value / quantity. 
            # We'll just look at the last positive receipt cost.
            stmt_hist = select(StockLedgerEntry.unit_cost).where(
                StockLedgerEntry.tenant_id == tenant_id,
                StockLedgerEntry.sku_id == line.sku_id,
                StockLedgerEntry.quantity > 0,
                StockLedgerEntry.unit_cost != None
            ).order_by(desc(StockLedgerEntry.created_at)).limit(1)
            
            last_cost = (await self.session.execute(stmt_hist)).scalar_one_or_none()
            
            if last_cost and last_cost > 0:
                variance = (line.unit_price - last_cost) / last_cost
                if variance > Decimal('0.10'): # 10% threshold
                    alert = OperationalAlert(
                        tenant_id=tenant_id,
                        location_id=None, # Price variance might not be location-specific if purchasing is central
                        sku_id=line.sku_id,
                        metric='PRICE_VARIANCE',
                        observed_value=line.unit_price,
                        reference_value=last_cost,
                        threshold=Decimal('0.10'),
                        reason=f"Invoice price ({line.unit_price}) is >10% higher than last cost ({last_cost}). Variance: {variance*100:.1f}%"
                    )
                    self.session.add(alert)
                    alerts.append(alert)
                    
        await self.session.flush()
        return alerts

    async def detect_dish_cmv_drift(
        self,
        tenant_id: UUID,
        threshold_percentage: float = 5.0
    ) -> List[Dict[str, Any]]:
        """
        Detects recipes whose current dynamically calculated cost per portion
        has drifted by more than threshold_percentage compared to target or historical baseline.
        """
        from modules.recipes.models import Recipe, RecipeVersion, RecipeIngredient
        from modules.costing.engine import CostingEngine
        from modules.catalog.models import SKU, UOM

        # 1. Fetch published recipes
        stmt = (
            select(Recipe, RecipeVersion)
            .join(RecipeVersion, Recipe.id == RecipeVersion.recipe_id)
            .where(
                Recipe.tenant_id == tenant_id,
                RecipeVersion.status == 'PUBLISHED',
                RecipeVersion.valid_to.is_(None)
            )
        )
        recipe_rows = (await self.session.execute(stmt)).all()

        drifted_dishes = []
        for recipe, version in recipe_rows:
            # Fetch ingredients
            stmt_ing = select(RecipeIngredient).where(
                RecipeIngredient.recipe_version_id == version.id,
                RecipeIngredient.tenant_id == tenant_id
            )
            ingredients = (await self.session.execute(stmt_ing)).scalars().all()

            total_cost = Decimal("0")
            for ing in ingredients:
                unit_cost = await CostingEngine.get_sku_cost(self.session, tenant_id, ing.sku_id)
                loss_factor = Decimal("1") + (Decimal(str(ing.loss_percentage or 0)) / Decimal("100"))
                adjusted_qty = Decimal(str(ing.quantity)) * loss_factor
                total_cost += adjusted_qty * unit_cost

            yield_qty = Decimal(str(version.yield_quantity)) if version.yield_quantity else Decimal("1")
            portion_size = Decimal(str(version.portion_size)) if version.portion_size else Decimal("1")
            portions = yield_qty / portion_size if portion_size > 0 else Decimal("1")
            current_portion_cost = total_cost / portions if portions > 0 else total_cost

            # Reference baseline (e.g. from version creation or last cost)
            # If current cost > 0, evaluate drift
            target_portion_cost = getattr(version, 'target_cost', None) or (current_portion_cost * Decimal("0.90")) # fallback baseline
            
            drift_pct = float(Decimal("0"))
            if target_portion_cost and target_portion_cost > 0:
                drift_pct = float(((current_portion_cost - Decimal(str(target_portion_cost))) / Decimal(str(target_portion_cost))) * Decimal("100"))

            if abs(drift_pct) >= threshold_percentage or current_portion_cost > 0:
                drifted_dishes.append({
                    "recipe_id": str(recipe.id),
                    "recipe_name": recipe.name,
                    "version_number": version.version_number,
                    "current_portion_cost": float(current_portion_cost),
                    "target_portion_cost": float(target_portion_cost) if target_portion_cost else float(current_portion_cost),
                    "drift_percentage": round(drift_pct, 2),
                    "status": "CRITICAL" if drift_pct >= 15.0 else ("WARNING" if drift_pct >= threshold_percentage else "NORMAL")
                })

        return drifted_dishes

    async def calculate_supplier_lead_time_stockouts(
        self,
        tenant_id: UUID,
        location_id: Optional[UUID] = None
    ) -> List[Dict[str, Any]]:
        """
        Calculates real-world replenishment lead times per supplier and projects stockout dates
        based on 30-day daily burn rate and current on-hand inventory.
        """
        from modules.catalog.models import SKU, UOM
        from modules.suppliers.models import Supplier

        cutoff_date = datetime.now(timezone.utc) - timedelta(days=30)

        # 1. Calculate historical supplier lead time (days from PO creation to Goods Receipt)
        stmt_lead = (
            select(
                PurchaseOrder.supplier_id,
                func.avg(
                    func.extract('epoch', GoodsReceipt.receipt_date - PurchaseOrder.created_at) / 86400.0
                ).label('avg_lead_days')
            )
            .join(GoodsReceipt, PurchaseOrder.id == GoodsReceipt.purchase_order_id)
            .where(
                PurchaseOrder.tenant_id == tenant_id,
                GoodsReceipt.receipt_date != None
            )
            .group_by(PurchaseOrder.supplier_id)
        )
        lead_rows = (await self.session.execute(stmt_lead)).all()
        supplier_lead_map = {r.supplier_id: max(1, int(round(float(r.avg_lead_days or 3)))) for r in lead_rows}

        # 2. Fetch active SKUs with policies and stock
        stmt_skus = (
            select(SKU, UOM, InventoryPolicy)
            .join(UOM, SKU.base_uom_id == UOM.id)
            .outerjoin(InventoryPolicy, (SKU.id == InventoryPolicy.sku_id) & (InventoryPolicy.tenant_id == tenant_id))
            .where(
                SKU.tenant_id == tenant_id,
                SKU.is_active == True
            )
        )
        if location_id:
            stmt_skus = stmt_skus.where((InventoryPolicy.location_id == location_id) | (InventoryPolicy.location_id.is_(None)))

        sku_records = (await self.session.execute(stmt_skus)).all()

        risks = []
        for sku, uom, policy in sku_records:
            # Calculate 30-day consumption
            stmt_cons = (
                select(func.coalesce(func.sum(func.abs(StockLedgerEntry.quantity)), Decimal(0)))
                .select_from(StockLedgerEntry)
                .join(StockMovement, StockLedgerEntry.movement_id == StockMovement.id)
                .where(
                    StockLedgerEntry.tenant_id == tenant_id,
                    StockLedgerEntry.sku_id == sku.id,
                    StockLedgerEntry.quantity < 0,
                    StockLedgerEntry.created_at >= cutoff_date
                )
            )
            if location_id:
                stmt_cons = stmt_cons.where(StockMovement.location_id == location_id)

            total_consumption_30d = Decimal(str((await self.session.execute(stmt_cons)).scalar_one()))
            daily_burn_rate = total_consumption_30d / Decimal("30")

            # Current stock on hand
            stmt_stock = select(func.coalesce(func.sum(StockBalanceProjection.quantity), Decimal(0))).where(
                StockBalanceProjection.tenant_id == tenant_id,
                StockBalanceProjection.sku_id == sku.id
            )
            if location_id:
                stmt_stock = stmt_stock.where(StockBalanceProjection.location_id == location_id)

            on_hand = Decimal(str((await self.session.execute(stmt_stock)).scalar_one()))

            # Effective lead time days
            lead_time_days = policy.lead_time_days if (policy and policy.lead_time_days) else 3

            # Days of stock remaining
            days_remaining = (on_hand / daily_burn_rate) if daily_burn_rate > 0 else Decimal("999")

            risk_level = "SAFE"
            if days_remaining <= Decimal(str(lead_time_days)):
                risk_level = "CRITICAL" # Will run out before replenishment arrives
            elif days_remaining <= Decimal(str(lead_time_days * 2)):
                risk_level = "WARNING"

            risks.append({
                "sku_id": str(sku.id),
                "sku_name": sku.name,
                "uom_symbol": uom.symbol,
                "on_hand": float(on_hand),
                "daily_burn_rate": float(round(daily_burn_rate, 4)),
                "days_remaining": min(999.0, float(round(days_remaining, 1))),
                "lead_time_days": lead_time_days,
                "risk_level": risk_level
            })

        return risks
