"""phase4_purchasing_reconciliation

Revision ID: 167956c9214c
Revises: 8fb1e626f7b0
Create Date: 2026-08-13 21:00:35.555486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '167956c9214c'
down_revision: Union[str, Sequence[str], None] = '8fb1e626f7b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('issue_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=24, scale=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_invoices_tenant_id'), 'supplier_invoices', ['tenant_id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('order_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expected_delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_tenant_id'), 'purchase_orders', ['tenant_id'], unique=False)
    op.create_table('purchase_order_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_id', sa.UUID(), nullable=False),
    sa.Column('sku_id', sa.UUID(), nullable=False),
    sa.Column('supplier_sku_id', sa.UUID(), nullable=True),
    sa.Column('ordered_quantity', sa.Numeric(precision=24, scale=12), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=24, scale=12), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_sku_id'], ['supplier_skus.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_order_lines_purchase_order_id'), 'purchase_order_lines', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_lines_tenant_id'), 'purchase_order_lines', ['tenant_id'], unique=False)
    op.create_table('supplier_invoice_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('sku_id', sa.UUID(), nullable=False),
    sa.Column('supplier_sku_id', sa.UUID(), nullable=True),
    sa.Column('invoiced_quantity', sa.Numeric(precision=24, scale=12), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=24, scale=12), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['supplier_invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_sku_id'], ['supplier_skus.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_invoice_lines_invoice_id'), 'supplier_invoice_lines', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_supplier_invoice_lines_tenant_id'), 'supplier_invoice_lines', ['tenant_id'], unique=False)
    op.create_table('purchase_reconciliations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_line_id', sa.UUID(), nullable=False),
    sa.Column('receipt_line_id', sa.UUID(), nullable=True),
    sa.Column('invoice_line_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['invoice_line_id'], ['supplier_invoice_lines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['purchase_order_line_id'], ['purchase_order_lines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receipt_line_id'], ['goods_receipt_lines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_reconciliations_invoice_line_id'), 'purchase_reconciliations', ['invoice_line_id'], unique=False)
    op.create_index(op.f('ix_purchase_reconciliations_purchase_order_line_id'), 'purchase_reconciliations', ['purchase_order_line_id'], unique=False)
    op.create_index(op.f('ix_purchase_reconciliations_receipt_line_id'), 'purchase_reconciliations', ['receipt_line_id'], unique=False)
    op.create_index(op.f('ix_purchase_reconciliations_tenant_id'), 'purchase_reconciliations', ['tenant_id'], unique=False)
    op.add_column('goods_receipt_lines', sa.Column('purchase_order_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_goods_receipt_lines_purchase_order_id'), 'goods_receipt_lines', ['purchase_order_id'], unique=False)
    op.create_foreign_key(None, 'goods_receipt_lines', 'purchase_orders', ['purchase_order_id'], ['id'], ondelete='RESTRICT')
    op.add_column('goods_receipts', sa.Column('purchase_order_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_goods_receipts_purchase_order_id'), 'goods_receipts', ['purchase_order_id'], unique=False)
    op.create_foreign_key(None, 'goods_receipts', 'purchase_orders', ['purchase_order_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###

    # --- Enable RLS ---
    tables = [
        'purchase_orders', 'purchase_order_lines', 
        'supplier_invoices', 'supplier_invoice_lines',
        'purchase_reconciliations'
    ]
    for table in tables:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY;")
        op.execute(f"CREATE POLICY tenant_isolation_policy ON {table} USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid);")
        
    # Grant permissions to the application role
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ksfoodops_app;")


def downgrade() -> None:
    """Downgrade schema."""
    # --- Disable RLS ---
    tables = [
        'purchase_orders', 'purchase_order_lines', 
        'supplier_invoices', 'supplier_invoice_lines',
        'purchase_reconciliations'
    ]
    for table in tables:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation_policy ON {table};")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'goods_receipts', type_='foreignkey')
    op.drop_index(op.f('ix_goods_receipts_purchase_order_id'), table_name='goods_receipts')
    op.drop_column('goods_receipts', 'purchase_order_id')
    op.drop_constraint(None, 'goods_receipt_lines', type_='foreignkey')
    op.drop_index(op.f('ix_goods_receipt_lines_purchase_order_id'), table_name='goods_receipt_lines')
    op.drop_column('goods_receipt_lines', 'purchase_order_id')
    op.drop_index(op.f('ix_purchase_reconciliations_tenant_id'), table_name='purchase_reconciliations')
    op.drop_index(op.f('ix_purchase_reconciliations_receipt_line_id'), table_name='purchase_reconciliations')
    op.drop_index(op.f('ix_purchase_reconciliations_purchase_order_line_id'), table_name='purchase_reconciliations')
    op.drop_index(op.f('ix_purchase_reconciliations_invoice_line_id'), table_name='purchase_reconciliations')
    op.drop_table('purchase_reconciliations')
    op.drop_index(op.f('ix_supplier_invoice_lines_tenant_id'), table_name='supplier_invoice_lines')
    op.drop_index(op.f('ix_supplier_invoice_lines_invoice_id'), table_name='supplier_invoice_lines')
    op.drop_table('supplier_invoice_lines')
    op.drop_index(op.f('ix_purchase_order_lines_tenant_id'), table_name='purchase_order_lines')
    op.drop_index(op.f('ix_purchase_order_lines_purchase_order_id'), table_name='purchase_order_lines')
    op.drop_table('purchase_order_lines')
    op.drop_index(op.f('ix_purchase_orders_tenant_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_supplier_invoices_tenant_id'), table_name='supplier_invoices')
    op.drop_table('supplier_invoices')
    # ### end Alembic commands ###
