"""phase5_retries

Revision ID: 1ef02fd6477c
Revises: a5a5d0dfa55b
Create Date: 2026-08-15 20:49:59.046717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ef02fd6477c'
down_revision: Union[str, Sequence[str], None] = 'a5a5d0dfa55b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox_messages', sa.Column('retry_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('outbox_messages', sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outbox_messages', 'next_retry_at')
    op.drop_column('outbox_messages', 'retry_count')
    # ### end Alembic commands ###
