"""phase5_recipes_and_sales

Revision ID: 215abd7f4dfc
Revises: 265297f2f58c
Create Date: 2026-08-13 21:57:26.073784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '215abd7f4dfc'
down_revision: Union[str, Sequence[str], None] = '265297f2f58c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('pos_code', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipes_tenant_id'), 'recipes', ['tenant_id'], unique=False)
    op.create_table('sales_imports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('pos_system', sa.String(length=100), nullable=False),
    sa.Column('import_reference', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_imports_tenant_id'), 'sales_imports', ['tenant_id'], unique=False)
    op.create_table('pos_product_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('pos_product_id', sa.String(length=100), nullable=False),
    sa.Column('pos_product_name', sa.String(length=255), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pos_product_mappings_tenant_id'), 'pos_product_mappings', ['tenant_id'], unique=False)
    op.create_table('recipe_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('yield_quantity', sa.Numeric(precision=24, scale=12), nullable=False),
    sa.Column('yield_uom_id', sa.UUID(), nullable=False),
    sa.Column('portion_size', sa.Numeric(precision=24, scale=12), nullable=False),
    sa.Column('portion_uom_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['portion_uom_id'], ['uoms.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['yield_uom_id'], ['uoms.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_versions_recipe_id'), 'recipe_versions', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_recipe_versions_tenant_id'), 'recipe_versions', ['tenant_id'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('sales_import_id', sa.UUID(), nullable=False),
    sa.Column('pos_sale_id', sa.String(length=100), nullable=False),
    sa.Column('sale_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=24, scale=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['sales_import_id'], ['sales_imports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_sales_import_id'), 'sales', ['sales_import_id'], unique=False)
    op.create_index(op.f('ix_sales_tenant_id'), 'sales', ['tenant_id'], unique=False)
    op.create_table('recipe_ingredients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('recipe_version_id', sa.UUID(), nullable=False),
    sa.Column('sku_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=12), nullable=False),
    sa.Column('uom_id', sa.UUID(), nullable=False),
    sa.Column('loss_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['recipe_version_id'], ['recipe_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uom_id'], ['uoms.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_ingredients_recipe_version_id'), 'recipe_ingredients', ['recipe_version_id'], unique=False)
    op.create_index(op.f('ix_recipe_ingredients_tenant_id'), 'recipe_ingredients', ['tenant_id'], unique=False)
    op.create_table('sale_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('sale_id', sa.UUID(), nullable=False),
    sa.Column('pos_product_id', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=12), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=24, scale=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_lines_sale_id'), 'sale_lines', ['sale_id'], unique=False)
    op.create_index(op.f('ix_sale_lines_tenant_id'), 'sale_lines', ['tenant_id'], unique=False)
    op.create_table('loss_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('movement_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['movement_id'], ['stock_movements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loss_records_movement_id'), 'loss_records', ['movement_id'], unique=False)
    op.create_index(op.f('ix_loss_records_tenant_id'), 'loss_records', ['tenant_id'], unique=False)
    op.create_table('theoretical_consumptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('sale_line_id', sa.UUID(), nullable=False),
    sa.Column('recipe_version_id', sa.UUID(), nullable=False),
    sa.Column('sku_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=12), nullable=False),
    sa.Column('unit_cost_at_time', sa.Numeric(precision=24, scale=12), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['recipe_version_id'], ['recipe_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sale_line_id'], ['sale_lines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_theoretical_consumptions_sale_line_id'), 'theoretical_consumptions', ['sale_line_id'], unique=False)
    op.create_index(op.f('ix_theoretical_consumptions_tenant_id'), 'theoretical_consumptions', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    # --- Enable RLS ---
    tables = [
        'recipes', 'recipe_versions', 'recipe_ingredients',
        'pos_product_mappings', 'sales_imports', 'sales', 'sale_lines',
        'loss_records', 'theoretical_consumptions'
    ]
    for table in tables:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY;")
        op.execute(f"CREATE POLICY tenant_isolation_policy ON {table} USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid);")
        
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ksfoodops_app;")

def downgrade() -> None:
    """Downgrade schema."""
    # --- Disable RLS ---
    tables = [
        'recipes', 'recipe_versions', 'recipe_ingredients',
        'pos_product_mappings', 'sales_imports', 'sales', 'sale_lines',
        'loss_records', 'theoretical_consumptions'
    ]
    for table in tables:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation_policy ON {table};")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_theoretical_consumptions_tenant_id'), table_name='theoretical_consumptions')
    op.drop_index(op.f('ix_theoretical_consumptions_sale_line_id'), table_name='theoretical_consumptions')
    op.drop_table('theoretical_consumptions')
    op.drop_index(op.f('ix_loss_records_tenant_id'), table_name='loss_records')
    op.drop_index(op.f('ix_loss_records_movement_id'), table_name='loss_records')
    op.drop_table('loss_records')
    op.drop_index(op.f('ix_sale_lines_tenant_id'), table_name='sale_lines')
    op.drop_index(op.f('ix_sale_lines_sale_id'), table_name='sale_lines')
    op.drop_table('sale_lines')
    op.drop_index(op.f('ix_recipe_ingredients_tenant_id'), table_name='recipe_ingredients')
    op.drop_index(op.f('ix_recipe_ingredients_recipe_version_id'), table_name='recipe_ingredients')
    op.drop_table('recipe_ingredients')
    op.drop_index(op.f('ix_sales_tenant_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_sales_import_id'), table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_recipe_versions_tenant_id'), table_name='recipe_versions')
    op.drop_index(op.f('ix_recipe_versions_recipe_id'), table_name='recipe_versions')
    op.drop_table('recipe_versions')
    op.drop_index(op.f('ix_pos_product_mappings_tenant_id'), table_name='pos_product_mappings')
    op.drop_table('pos_product_mappings')
    op.drop_index(op.f('ix_sales_imports_tenant_id'), table_name='sales_imports')
    op.drop_table('sales_imports')
    op.drop_index(op.f('ix_recipes_tenant_id'), table_name='recipes')
    op.drop_table('recipes')
    # ### end Alembic commands ###
