"""fix_goods_receipt_line_fk

Revision ID: 265297f2f58c
Revises: 167956c9214c
Create Date: 2026-08-13 21:21:04.826555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '265297f2f58c'
down_revision: Union[str, Sequence[str], None] = '167956c9214c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods_receipt_lines', sa.Column('purchase_order_line_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_goods_receipt_lines_purchase_order_id'), table_name='goods_receipt_lines')
    op.create_index(op.f('ix_goods_receipt_lines_purchase_order_line_id'), 'goods_receipt_lines', ['purchase_order_line_id'], unique=False)
    op.drop_constraint(op.f('goods_receipt_lines_purchase_order_id_fkey'), 'goods_receipt_lines', type_='foreignkey')
    op.create_foreign_key(None, 'goods_receipt_lines', 'purchase_order_lines', ['purchase_order_line_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('goods_receipt_lines', 'purchase_order_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods_receipt_lines', sa.Column('purchase_order_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'goods_receipt_lines', type_='foreignkey')
    op.create_foreign_key(op.f('goods_receipt_lines_purchase_order_id_fkey'), 'goods_receipt_lines', 'purchase_orders', ['purchase_order_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_goods_receipt_lines_purchase_order_line_id'), table_name='goods_receipt_lines')
    op.create_index(op.f('ix_goods_receipt_lines_purchase_order_id'), 'goods_receipt_lines', ['purchase_order_id'], unique=False)
    op.drop_column('goods_receipt_lines', 'purchase_order_line_id')
    # ### end Alembic commands ###
