"""Initial tenant models with RLS

Revision ID: 313a6cd2aed7
Revises: 
Create Date: 2026-08-13 07:33:19.383871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '313a6cd2aed7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenant_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('business_unit_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['business_unit_id'], ['business_units.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # --- Manual RLS and Security Setup ---
    # Create the application role if it doesn't exist (handle safely)
    op.execute("""
    DO $$
    BEGIN
      IF NOT EXISTS (
        SELECT FROM pg_catalog.pg_roles
        WHERE  rolname = 'ksfoodops_app') THEN
        CREATE ROLE ksfoodops_app WITH LOGIN PASSWORD 'app_password' NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS;
      END IF;
    END
    $$;
    """)

    # Grant permissions to the application role
    op.execute("DO $$ BEGIN EXECUTE format('GRANT CONNECT ON DATABASE %I TO ksfoodops_app', current_database()); END $$;")
    op.execute("GRANT USAGE ON SCHEMA public TO ksfoodops_app;")
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ksfoodops_app;")
    
    # RLS for business_units
    op.execute("ALTER TABLE business_units ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE business_units FORCE ROW LEVEL SECURITY;")
    op.execute("CREATE POLICY tenant_isolation_policy ON business_units USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid);")

    # RLS for locations
    op.execute("ALTER TABLE locations ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE locations FORCE ROW LEVEL SECURITY;")
    op.execute("CREATE POLICY tenant_isolation_policy ON locations USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid);")

    # RLS for tenant_memberships
    op.execute("ALTER TABLE tenant_memberships ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE tenant_memberships FORCE ROW LEVEL SECURITY;")
    op.execute("CREATE POLICY tenant_isolation_policy ON tenant_memberships USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid);")



def downgrade() -> None:
    """Downgrade schema."""
    # --- Manual RLS and Security Teardown ---
    op.execute("DROP POLICY IF EXISTS tenant_isolation_policy ON tenant_memberships;")
    op.execute("DROP POLICY IF EXISTS tenant_isolation_policy ON locations;")
    op.execute("DROP POLICY IF EXISTS tenant_isolation_policy ON business_units;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('locations')
    op.drop_table('tenant_memberships')
    op.drop_table('business_units')
    op.drop_table('tenants')
    # ### end Alembic commands ###
