"""phase7_documents

Revision ID: 3635da773fa4
Revises: c2fa8c618622
Create Date: 2026-08-16 05:29:20.121527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3635da773fa4'
down_revision: Union[str, Sequence[str], None] = 'c2fa8c618622'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_uploads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('file_hash', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('format', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_uploads_file_hash'), 'document_uploads', ['file_hash'], unique=False)
    op.create_index(op.f('ix_document_uploads_tenant_id'), 'document_uploads', ['tenant_id'], unique=False)
    op.add_column('document_extraction_lines', sa.Column('normalized_sku_id', sa.UUID(), nullable=True))
    op.add_column('document_extraction_lines', sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True))
    op.alter_column('document_extraction_lines', 'raw_description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_constraint(op.f('document_extraction_lines_supplier_sku_id_fkey'), 'document_extraction_lines', type_='foreignkey')
    op.drop_constraint(op.f('document_extraction_lines_sku_id_fkey'), 'document_extraction_lines', type_='foreignkey')
    op.create_foreign_key(None, 'document_extraction_lines', 'skus', ['normalized_sku_id'], ['id'], ondelete='SET NULL')
    op.drop_column('document_extraction_lines', 'sku_id')
    op.drop_column('document_extraction_lines', 'match_status')
    op.drop_column('document_extraction_lines', 'supplier_sku_id')
    op.add_column('document_extractions', sa.Column('document_upload_id', sa.UUID(), nullable=False))
    op.add_column('document_extractions', sa.Column('supplier_cnpj_candidate', sa.String(length=50), nullable=True))
    op.add_column('document_extractions', sa.Column('supplier_name_candidate', sa.String(length=255), nullable=True))
    op.add_column('document_extractions', sa.Column('invoice_number_candidate', sa.String(length=100), nullable=True))
    op.add_column('document_extractions', sa.Column('total_amount_candidate', sa.Numeric(precision=24, scale=12), nullable=True))
    op.add_column('document_extractions', sa.Column('issue_date_candidate', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_document_extractions_raw_document_id'), table_name='document_extractions')
    op.create_unique_constraint(None, 'document_extractions', ['document_upload_id'])
    op.drop_constraint(op.f('document_extractions_raw_document_id_fkey'), 'document_extractions', type_='foreignkey')
    op.drop_constraint(op.f('document_extractions_supplier_id_fkey'), 'document_extractions', type_='foreignkey')
    op.create_foreign_key(None, 'document_extractions', 'document_uploads', ['document_upload_id'], ['id'], ondelete='CASCADE')
    op.drop_column('document_extractions', 'raw_document_id')
    op.drop_column('document_extractions', 'total_amount')
    op.drop_column('document_extractions', 'issue_date')
    op.drop_column('document_extractions', 'status')
    op.drop_column('document_extractions', 'supplier_id')
    op.drop_column('document_extractions', 'invoice_number')
    
    op.drop_index(op.f('ix_raw_documents_file_hash'), table_name='raw_documents')
    op.drop_index(op.f('ix_raw_documents_tenant_id'), table_name='raw_documents')
    op.drop_table('raw_documents')
    
    op.drop_index(op.f('ix_document_extraction_fields_parent_entity_id'), table_name='document_extraction_fields')
    op.drop_index(op.f('ix_document_extraction_fields_tenant_id'), table_name='document_extraction_fields')
    op.drop_table('document_extraction_fields')
    
    op.execute("ALTER TABLE document_uploads ENABLE ROW LEVEL SECURITY")
    op.execute("CREATE POLICY tenant_isolation_policy ON document_uploads USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid) WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid)")
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON document_uploads, document_extractions, document_extraction_lines TO ksfoodops_app")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("REVOKE SELECT, INSERT, UPDATE, DELETE ON document_uploads, document_extractions, document_extraction_lines FROM ksfoodops_app")
    op.execute("DROP POLICY IF EXISTS tenant_isolation_policy ON document_uploads")
    op.add_column('document_extractions', sa.Column('invoice_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('document_extractions', sa.Column('supplier_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('document_extractions', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('document_extractions', sa.Column('issue_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('document_extractions', sa.Column('total_amount', sa.NUMERIC(precision=24, scale=12), autoincrement=False, nullable=True))
    op.add_column('document_extractions', sa.Column('raw_document_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'document_extractions', type_='foreignkey')
    op.create_foreign_key(op.f('document_extractions_supplier_id_fkey'), 'document_extractions', 'suppliers', ['supplier_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('document_extractions_raw_document_id_fkey'), 'document_extractions', 'raw_documents', ['raw_document_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'document_extractions', type_='unique')
    op.create_index(op.f('ix_document_extractions_raw_document_id'), 'document_extractions', ['raw_document_id'], unique=False)
    op.drop_column('document_extractions', 'issue_date_candidate')
    op.drop_column('document_extractions', 'total_amount_candidate')
    op.drop_column('document_extractions', 'invoice_number_candidate')
    op.drop_column('document_extractions', 'supplier_name_candidate')
    op.drop_column('document_extractions', 'supplier_cnpj_candidate')
    op.drop_column('document_extractions', 'document_upload_id')
    op.add_column('document_extraction_lines', sa.Column('supplier_sku_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('document_extraction_lines', sa.Column('match_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('document_extraction_lines', sa.Column('sku_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'document_extraction_lines', type_='foreignkey')
    op.create_foreign_key(op.f('document_extraction_lines_sku_id_fkey'), 'document_extraction_lines', 'skus', ['sku_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('document_extraction_lines_supplier_sku_id_fkey'), 'document_extraction_lines', 'supplier_skus', ['supplier_sku_id'], ['id'], ondelete='SET NULL')
    op.alter_column('document_extraction_lines', 'raw_description',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_column('document_extraction_lines', 'confidence_score')
    op.drop_column('document_extraction_lines', 'normalized_sku_id')
    op.drop_column('document_extraction_lines', 'normalized_sku_id')
    op.create_table('document_extraction_fields',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('parent_entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('parent_entity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('field_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('raw_value', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('normalized_candidate', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('document_extraction_fields_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('document_extraction_fields_pkey'))
    )
    op.create_index(op.f('ix_document_extraction_fields_tenant_id'), 'document_extraction_fields', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_document_extraction_fields_parent_entity_id'), 'document_extraction_fields', ['parent_entity_id'], unique=False)
    op.create_table('raw_documents',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('file_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('document_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('raw_documents_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('raw_documents_pkey'))
    )
    op.create_index(op.f('ix_raw_documents_tenant_id'), 'raw_documents', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_raw_documents_file_hash'), 'raw_documents', ['file_hash'], unique=False)
    op.drop_index(op.f('ix_document_uploads_tenant_id'), table_name='document_uploads')
    op.drop_index(op.f('ix_document_uploads_file_hash'), table_name='document_uploads')
    op.drop_table('document_uploads')
    # ### end Alembic commands ###
