"""phase3_inventory_sessions

Revision ID: 8fb1e626f7b0
Revises: cb34f9ef3350
Create Date: 2026-08-13 20:32:11.187796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fb1e626f7b0'
down_revision: Union[str, Sequence[str], None] = 'cb34f9ef3350'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('cutoff_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_sessions_tenant_id'), 'inventory_sessions', ['tenant_id'], unique=False)
    op.create_table('inventory_close_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('sku_id', sa.UUID(), nullable=False),
    sa.Column('expected_quantity', sa.Numeric(precision=24, scale=12), nullable=False),
    sa.Column('counted_quantity', sa.Numeric(precision=24, scale=12), nullable=False),
    sa.Column('variance_quantity', sa.Numeric(precision=24, scale=12), nullable=False),
    sa.Column('variance_value', sa.Numeric(precision=24, scale=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['inventory_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_close_results_session_id'), 'inventory_close_results', ['session_id'], unique=False)
    op.create_index(op.f('ix_inventory_close_results_tenant_id'), 'inventory_close_results', ['tenant_id'], unique=False)
    op.create_table('inventory_count_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('sku_id', sa.UUID(), nullable=False),
    sa.Column('counted_quantity', sa.Numeric(precision=24, scale=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['inventory_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_count_lines_session_id'), 'inventory_count_lines', ['session_id'], unique=False)
    op.create_index(op.f('ix_inventory_count_lines_tenant_id'), 'inventory_count_lines', ['tenant_id'], unique=False)
    op.create_table('inventory_session_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['inventory_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_session_locations_session_id'), 'inventory_session_locations', ['session_id'], unique=False)
    op.create_index(op.f('ix_inventory_session_locations_tenant_id'), 'inventory_session_locations', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    # --- Enable RLS ---
    tables = [
        'inventory_sessions', 'inventory_session_locations', 
        'inventory_count_lines', 'inventory_close_results'
    ]
    for table in tables:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY;")
        op.execute(f"CREATE POLICY tenant_isolation_policy ON {table} USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid);")
        
    # Grant permissions to the application role
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ksfoodops_app;")


def downgrade() -> None:
    """Downgrade schema."""
    # --- Disable RLS ---
    tables = [
        'inventory_sessions', 'inventory_session_locations', 
        'inventory_count_lines', 'inventory_close_results'
    ]
    for table in tables:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation_policy ON {table};")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_session_locations_tenant_id'), table_name='inventory_session_locations')
    op.drop_index(op.f('ix_inventory_session_locations_session_id'), table_name='inventory_session_locations')
    op.drop_table('inventory_session_locations')
    op.drop_index(op.f('ix_inventory_count_lines_tenant_id'), table_name='inventory_count_lines')
    op.drop_index(op.f('ix_inventory_count_lines_session_id'), table_name='inventory_count_lines')
    op.drop_table('inventory_count_lines')
    op.drop_index(op.f('ix_inventory_close_results_tenant_id'), table_name='inventory_close_results')
    op.drop_index(op.f('ix_inventory_close_results_session_id'), table_name='inventory_close_results')
    op.drop_table('inventory_close_results')
    op.drop_index(op.f('ix_inventory_sessions_tenant_id'), table_name='inventory_sessions')
    op.drop_table('inventory_sessions')
    # ### end Alembic commands ###
