"""phase6_accounting_periods

Revision ID: c2fa8c618622
Revises: 1ef02fd6477c
Create Date: 2026-08-15 21:04:02.797525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2fa8c618622'
down_revision: Union[str, Sequence[str], None] = '1ef02fd6477c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounting_periods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounting_periods_tenant_id'), 'accounting_periods', ['tenant_id'], unique=False)
    op.create_index('IX_stock_ledger_entries_tenant_sku_date', 'stock_ledger_entries', ['tenant_id', 'sku_id', 'created_at'], unique=False)
    op.execute("ALTER TABLE accounting_periods ENABLE ROW LEVEL SECURITY")
    op.execute("CREATE POLICY tenant_isolation_policy ON accounting_periods USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid) WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid)")
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON accounting_periods TO ksfoodops_app")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("REVOKE SELECT, INSERT, UPDATE, DELETE ON accounting_periods FROM ksfoodops_app")
    op.execute("DROP POLICY IF EXISTS tenant_isolation_policy ON accounting_periods")
    op.drop_index('IX_stock_ledger_entries_tenant_sku_date', table_name='stock_ledger_entries')
    op.drop_index(op.f('ix_accounting_periods_tenant_id'), table_name='accounting_periods')
    op.drop_table('accounting_periods')
    # ### end Alembic commands ###
