"""phase2_inventory_slice

Revision ID: cb34f9ef3350
Revises: 313a6cd2aed7
Create Date: 2026-08-13 19:18:08.637633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb34f9ef3350'
down_revision: Union[str, Sequence[str], None] = '313a6cd2aed7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_tenant_id'), 'categories', ['tenant_id'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_tenant_id'), 'suppliers', ['tenant_id'], unique=False)
    op.create_table('uoms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('base_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uoms_tenant_id'), 'uoms', ['tenant_id'], unique=False)
    op.create_table('skus',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('base_uom_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['base_uom_id'], ['uoms.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skus_tenant_id'), 'skus', ['tenant_id'], unique=False)
    op.create_table('goods_receipts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('receipt_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goods_receipts_tenant_id'), 'goods_receipts', ['tenant_id'], unique=False)
    op.create_table('sku_conversion_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('sku_id', sa.UUID(), nullable=False),
    sa.Column('from_uom_id', sa.UUID(), nullable=False),
    sa.Column('to_uom_id', sa.UUID(), nullable=False),
    sa.Column('factor', sa.Numeric(precision=24, scale=12), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['from_uom_id'], ['uoms.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_uom_id'], ['uoms.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sku_conversion_versions_tenant_id'), 'sku_conversion_versions', ['tenant_id'], unique=False)
    op.create_table('stock_balance_projections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('sku_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=12), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=24, scale=12), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_balance_projections_tenant_id'), 'stock_balance_projections', ['tenant_id'], unique=False)
    op.create_table('stock_movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('reference_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_movements_tenant_id'), 'stock_movements', ['tenant_id'], unique=False)
    op.create_table('stock_ledger_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('movement_id', sa.UUID(), nullable=False),
    sa.Column('sku_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=12), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=24, scale=12), nullable=True),
    sa.Column('conversion_version_id', sa.UUID(), nullable=True),
    sa.Column('balance_after', sa.Numeric(precision=24, scale=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['conversion_version_id'], ['sku_conversion_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['movement_id'], ['stock_movements.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_ledger_entries_movement_id'), 'stock_ledger_entries', ['movement_id'], unique=False)
    op.create_index(op.f('ix_stock_ledger_entries_tenant_id'), 'stock_ledger_entries', ['tenant_id'], unique=False)
    op.create_table('supplier_skus',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('sku_id', sa.UUID(), nullable=False),
    sa.Column('supplier_item_code', sa.String(length=100), nullable=True),
    sa.Column('supplier_uom_id', sa.UUID(), nullable=True),
    sa.Column('default_conversion_version_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['default_conversion_version_id'], ['sku_conversion_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_uom_id'], ['uoms.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_skus_tenant_id'), 'supplier_skus', ['tenant_id'], unique=False)
    op.create_table('goods_receipt_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('receipt_id', sa.UUID(), nullable=False),
    sa.Column('sku_id', sa.UUID(), nullable=False),
    sa.Column('supplier_sku_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=24, scale=12), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=24, scale=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['receipt_id'], ['goods_receipts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_sku_id'], ['supplier_skus.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goods_receipt_lines_receipt_id'), 'goods_receipt_lines', ['receipt_id'], unique=False)
    op.create_index(op.f('ix_goods_receipt_lines_tenant_id'), 'goods_receipt_lines', ['tenant_id'], unique=False)
    op.create_table('supplier_sku_aliases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('supplier_sku_id', sa.UUID(), nullable=False),
    sa.Column('alias_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['supplier_sku_id'], ['supplier_skus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_sku_aliases_tenant_id'), 'supplier_sku_aliases', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    # --- Enable RLS ---
    tables = [
        'categories', 'suppliers', 'uoms', 'skus', 'goods_receipts', 
        'sku_conversion_versions', 'stock_balance_projections', 'stock_movements', 
        'stock_ledger_entries', 'supplier_skus', 'goods_receipt_lines', 'supplier_sku_aliases'
    ]
    for table in tables:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY;")
        op.execute(f"CREATE POLICY tenant_isolation_policy ON {table} USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid);")
        
    # Grant permissions to the application role
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ksfoodops_app;")



def downgrade() -> None:
    """Downgrade schema."""
    # --- Disable RLS ---
    tables = [
        'categories', 'suppliers', 'uoms', 'skus', 'goods_receipts', 
        'sku_conversion_versions', 'stock_balance_projections', 'stock_movements', 
        'stock_ledger_entries', 'supplier_skus', 'goods_receipt_lines', 'supplier_sku_aliases'
    ]
    for table in tables:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation_policy ON {table};")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supplier_sku_aliases_tenant_id'), table_name='supplier_sku_aliases')
    op.drop_table('supplier_sku_aliases')
    op.drop_index(op.f('ix_goods_receipt_lines_tenant_id'), table_name='goods_receipt_lines')
    op.drop_index(op.f('ix_goods_receipt_lines_receipt_id'), table_name='goods_receipt_lines')
    op.drop_table('goods_receipt_lines')
    op.drop_index(op.f('ix_supplier_skus_tenant_id'), table_name='supplier_skus')
    op.drop_table('supplier_skus')
    op.drop_index(op.f('ix_stock_ledger_entries_tenant_id'), table_name='stock_ledger_entries')
    op.drop_index(op.f('ix_stock_ledger_entries_movement_id'), table_name='stock_ledger_entries')
    op.drop_table('stock_ledger_entries')
    op.drop_index(op.f('ix_stock_movements_tenant_id'), table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index(op.f('ix_stock_balance_projections_tenant_id'), table_name='stock_balance_projections')
    op.drop_table('stock_balance_projections')
    op.drop_index(op.f('ix_sku_conversion_versions_tenant_id'), table_name='sku_conversion_versions')
    op.drop_table('sku_conversion_versions')
    op.drop_index(op.f('ix_goods_receipts_tenant_id'), table_name='goods_receipts')
    op.drop_table('goods_receipts')
    op.drop_index(op.f('ix_skus_tenant_id'), table_name='skus')
    op.drop_table('skus')
    op.drop_index(op.f('ix_uoms_tenant_id'), table_name='uoms')
    op.drop_table('uoms')
    op.drop_index(op.f('ix_suppliers_tenant_id'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_categories_tenant_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
